apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: pvc-from-snap 
spec: 
  accessModes: 
    - ReadWriteOnce 
  storageClassName: premium-csi
  resources: 
    requests: 
      storage: 3Gi 
  dataSource: 
    name: basic-snapshot 
    kind: VolumeSnapshot 
    apiGroup: snapshot.storage.k8s.io 

